services:
  edge:
    build:
      context: ./edge
    ports:
      - "8082:8080"
    depends_on:
      - app
    restart: always

  app:
    build:
      context: .
      args:
        VITE_SUPABASE_URL: ${VITE_SUPABASE_URL}
        VITE_SUPABASE_PUBLISHABLE_KEY: ${VITE_SUPABASE_PUBLISHABLE_KEY}
        VITE_SUPABASE_PROJECT_ID: ${VITE_SUPABASE_PROJECT_ID}
    expose:
      - "8080"
    restart: always
