/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as ScienceRouteImport } from './routes/science'
import { Route as MarketplaceIndexRouteImport } from './routes/marketplace.index'
import { Route as MarketplaceIdRouteImport } from './routes/marketplace.$id'
import { Route as MarketplaceRecommendationsRouteImport } from './routes/marketplace.recommendations'
import { Route as ParentDashboardRouteImport } from './routes/parent.dashboard'
import { Route as VendorAddProductRouteImport } from './routes/vendor.add-product'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const ScienceRoute = ScienceRouteImport.update({
  id: '/science',
  path: '/science',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketplaceIndexRoute = MarketplaceIndexRouteImport.update({
  id: '/marketplace/',
  path: '/marketplace/',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketplaceIdRoute = MarketplaceIdRouteImport.update({
  id: '/marketplace/$id',
  path: '/marketplace/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketplaceRecommendationsRoute =
  MarketplaceRecommendationsRouteImport.update({
    id: '/marketplace/recommendations',
    path: '/marketplace/recommendations',
    getParentRoute: () => rootRouteImport,
  } as any)
const ParentDashboardRoute = ParentDashboardRouteImport.update({
  id: '/parent/dashboard',
  path: '/parent/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const VendorAddProductRoute = VendorAddProductRouteImport.update({
  id: '/vendor/add-product',
  path: '/vendor/add-product',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/science': typeof ScienceRoute
  '/marketplace/$id': typeof MarketplaceIdRoute
  '/marketplace/recommendations': typeof MarketplaceRecommendationsRoute
  '/parent/dashboard': typeof ParentDashboardRoute
  '/vendor/add-product': typeof VendorAddProductRoute
  '/marketplace/': typeof MarketplaceIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/science': typeof ScienceRoute
  '/marketplace/$id': typeof MarketplaceIdRoute
  '/marketplace/recommendations': typeof MarketplaceRecommendationsRoute
  '/parent/dashboard': typeof ParentDashboardRoute
  '/vendor/add-product': typeof VendorAddProductRoute
  '/marketplace': typeof MarketplaceIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/science': typeof ScienceRoute
  '/marketplace/$id': typeof MarketplaceIdRoute
  '/marketplace/recommendations': typeof MarketplaceRecommendationsRoute
  '/parent/dashboard': typeof ParentDashboardRoute
  '/vendor/add-product': typeof VendorAddProductRoute
  '/marketplace/': typeof MarketplaceIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/analytics'
    | '/science'
    | '/marketplace/$id'
    | '/marketplace/recommendations'
    | '/parent/dashboard'
    | '/vendor/add-product'
    | '/marketplace/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/analytics'
    | '/science'
    | '/marketplace/$id'
    | '/marketplace/recommendations'
    | '/parent/dashboard'
    | '/vendor/add-product'
    | '/marketplace'
  id:
    | '__root__'
    | '/'
    | '/analytics'
    | '/science'
    | '/marketplace/$id'
    | '/marketplace/recommendations'
    | '/parent/dashboard'
    | '/vendor/add-product'
    | '/marketplace/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnalyticsRoute: typeof AnalyticsRoute
  ScienceRoute: typeof ScienceRoute
  MarketplaceIdRoute: typeof MarketplaceIdRoute
  MarketplaceRecommendationsRoute: typeof MarketplaceRecommendationsRoute
  ParentDashboardRoute: typeof ParentDashboardRoute
  VendorAddProductRoute: typeof VendorAddProductRoute
  MarketplaceIndexRoute: typeof MarketplaceIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/science': {
      id: '/science'
      path: '/science'
      fullPath: '/science'
      preLoaderRoute: typeof ScienceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marketplace/': {
      id: '/marketplace/'
      path: '/marketplace'
      fullPath: '/marketplace/'
      preLoaderRoute: typeof MarketplaceIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marketplace/$id': {
      id: '/marketplace/$id'
      path: '/marketplace/$id'
      fullPath: '/marketplace/$id'
      preLoaderRoute: typeof MarketplaceIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marketplace/recommendations': {
      id: '/marketplace/recommendations'
      path: '/marketplace/recommendations'
      fullPath: '/marketplace/recommendations'
      preLoaderRoute: typeof MarketplaceRecommendationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parent/dashboard': {
      id: '/parent/dashboard'
      path: '/parent/dashboard'
      fullPath: '/parent/dashboard'
      preLoaderRoute: typeof ParentDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vendor/add-product': {
      id: '/vendor/add-product'
      path: '/vendor/add-product'
      fullPath: '/vendor/add-product'
      preLoaderRoute: typeof VendorAddProductRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnalyticsRoute: AnalyticsRoute,
  ScienceRoute: ScienceRoute,
  MarketplaceIdRoute: MarketplaceIdRoute,
  MarketplaceRecommendationsRoute: MarketplaceRecommendationsRoute,
  ParentDashboardRoute: ParentDashboardRoute,
  VendorAddProductRoute: VendorAddProductRoute,
  MarketplaceIndexRoute: MarketplaceIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
