/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as InstructionsRouteImport } from './routes/instructions'
import { Route as PrivacyPolicyRouteImport } from './routes/privacy-policy'
import { Route as RegistryRouteImport } from './routes/registry'
import { Route as ScienceRouteImport } from './routes/science'
import { Route as AuthCallbackRouteImport } from './routes/auth.callback'
import { Route as MarketplaceIndexRouteImport } from './routes/marketplace.index'
import { Route as MarketplaceIdRouteImport } from './routes/marketplace.$id'
import { Route as MarketplaceRecommendationsRouteImport } from './routes/marketplace.recommendations'
import { Route as VendorAddProductRouteImport } from './routes/vendor.add-product'
import { Route as AuthenticatedParentDashboardRouteImport } from './routes/_authenticated.parent.dashboard'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const InstructionsRoute = InstructionsRouteImport.update({
  id: '/instructions',
  path: '/instructions',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyPolicyRoute = PrivacyPolicyRouteImport.update({
  id: '/privacy-policy',
  path: '/privacy-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const RegistryRoute = RegistryRouteImport.update({
  id: '/registry',
  path: '/registry',
  getParentRoute: () => rootRouteImport,
} as any)
const ScienceRoute = ScienceRouteImport.update({
  id: '/science',
  path: '/science',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/callback',
  path: '/callback',
  getParentRoute: () => AuthRoute,
} as any)
const MarketplaceIndexRoute = MarketplaceIndexRouteImport.update({
  id: '/marketplace/',
  path: '/marketplace/',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketplaceIdRoute = MarketplaceIdRouteImport.update({
  id: '/marketplace/$id',
  path: '/marketplace/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketplaceRecommendationsRoute =
  MarketplaceRecommendationsRouteImport.update({
    id: '/marketplace/recommendations',
    path: '/marketplace/recommendations',
    getParentRoute: () => rootRouteImport,
  } as any)
const VendorAddProductRoute = VendorAddProductRouteImport.update({
  id: '/vendor/add-product',
  path: '/vendor/add-product',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedParentDashboardRoute =
  AuthenticatedParentDashboardRouteImport.update({
    id: '/parent/dashboard',
    path: '/parent/dashboard',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/auth': typeof AuthRouteWithChildren
  '/instructions': typeof InstructionsRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/registry': typeof RegistryRoute
  '/science': typeof ScienceRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/marketplace/$id': typeof MarketplaceIdRoute
  '/marketplace/recommendations': typeof MarketplaceRecommendationsRoute
  '/vendor/add-product': typeof VendorAddProductRoute
  '/marketplace/': typeof MarketplaceIndexRoute
  '/parent/dashboard': typeof AuthenticatedParentDashboardRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/auth': typeof AuthRouteWithChildren
  '/instructions': typeof InstructionsRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/registry': typeof RegistryRoute
  '/science': typeof ScienceRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/marketplace/$id': typeof MarketplaceIdRoute
  '/marketplace/recommendations': typeof MarketplaceRecommendationsRoute
  '/vendor/add-product': typeof VendorAddProductRoute
  '/marketplace': typeof MarketplaceIndexRoute
  '/parent/dashboard': typeof AuthenticatedParentDashboardRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/analytics': typeof AnalyticsRoute
  '/auth': typeof AuthRouteWithChildren
  '/instructions': typeof InstructionsRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/registry': typeof RegistryRoute
  '/science': typeof ScienceRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/marketplace/$id': typeof MarketplaceIdRoute
  '/marketplace/recommendations': typeof MarketplaceRecommendationsRoute
  '/vendor/add-product': typeof VendorAddProductRoute
  '/marketplace/': typeof MarketplaceIndexRoute
  '/_authenticated/parent/dashboard': typeof AuthenticatedParentDashboardRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/analytics'
    | '/auth'
    | '/instructions'
    | '/privacy-policy'
    | '/registry'
    | '/science'
    | '/auth/callback'
    | '/marketplace/$id'
    | '/marketplace/recommendations'
    | '/vendor/add-product'
    | '/marketplace/'
    | '/parent/dashboard'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/analytics'
    | '/auth'
    | '/instructions'
    | '/privacy-policy'
    | '/registry'
    | '/science'
    | '/auth/callback'
    | '/marketplace/$id'
    | '/marketplace/recommendations'
    | '/vendor/add-product'
    | '/marketplace'
    | '/parent/dashboard'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/analytics'
    | '/auth'
    | '/instructions'
    | '/privacy-policy'
    | '/registry'
    | '/science'
    | '/auth/callback'
    | '/marketplace/$id'
    | '/marketplace/recommendations'
    | '/vendor/add-product'
    | '/marketplace/'
    | '/_authenticated/parent/dashboard'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AnalyticsRoute: typeof AnalyticsRoute
  AuthRoute: typeof AuthRouteWithChildren
  InstructionsRoute: typeof InstructionsRoute
  PrivacyPolicyRoute: typeof PrivacyPolicyRoute
  RegistryRoute: typeof RegistryRoute
  ScienceRoute: typeof ScienceRoute
  MarketplaceIdRoute: typeof MarketplaceIdRoute
  MarketplaceRecommendationsRoute: typeof MarketplaceRecommendationsRoute
  VendorAddProductRoute: typeof VendorAddProductRoute
  MarketplaceIndexRoute: typeof MarketplaceIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/instructions': {
      id: '/instructions'
      path: '/instructions'
      fullPath: '/instructions'
      preLoaderRoute: typeof InstructionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy-policy': {
      id: '/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/privacy-policy'
      preLoaderRoute: typeof PrivacyPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/registry': {
      id: '/registry'
      path: '/registry'
      fullPath: '/registry'
      preLoaderRoute: typeof RegistryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/science': {
      id: '/science'
      path: '/science'
      fullPath: '/science'
      preLoaderRoute: typeof ScienceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof AuthRoute
    }
    '/marketplace/': {
      id: '/marketplace/'
      path: '/marketplace'
      fullPath: '/marketplace/'
      preLoaderRoute: typeof MarketplaceIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marketplace/$id': {
      id: '/marketplace/$id'
      path: '/marketplace/$id'
      fullPath: '/marketplace/$id'
      preLoaderRoute: typeof MarketplaceIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marketplace/recommendations': {
      id: '/marketplace/recommendations'
      path: '/marketplace/recommendations'
      fullPath: '/marketplace/recommendations'
      preLoaderRoute: typeof MarketplaceRecommendationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vendor/add-product': {
      id: '/vendor/add-product'
      path: '/vendor/add-product'
      fullPath: '/vendor/add-product'
      preLoaderRoute: typeof VendorAddProductRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/parent/dashboard': {
      id: '/_authenticated/parent/dashboard'
      path: '/parent/dashboard'
      fullPath: '/parent/dashboard'
      preLoaderRoute: typeof AuthenticatedParentDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedParentDashboardRoute: typeof AuthenticatedParentDashboardRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedParentDashboardRoute: AuthenticatedParentDashboardRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

interface AuthRouteChildren {
  AuthCallbackRoute: typeof AuthCallbackRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthCallbackRoute: AuthCallbackRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AnalyticsRoute: AnalyticsRoute,
  AuthRoute: AuthRouteWithChildren,
  InstructionsRoute: InstructionsRoute,
  PrivacyPolicyRoute: PrivacyPolicyRoute,
  RegistryRoute: RegistryRoute,
  ScienceRoute: ScienceRoute,
  MarketplaceIdRoute: MarketplaceIdRoute,
  MarketplaceRecommendationsRoute: MarketplaceRecommendationsRoute,
  VendorAddProductRoute: VendorAddProductRoute,
  MarketplaceIndexRoute: MarketplaceIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
